name: End to end tests
on:
  push:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.list-scenarios.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v3
      - id: list-scenarios
        run: |
          pip install gherkin-official
          python .github/scripts/list_scenarios.py
  run-e2e-tests:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        scenario: ${{ fromJSON(needs.setup.outputs.scenarios) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          import json
          with open("payload.json", 'a') as p:
            print(json.dumps(${{ toJSON(matrix.scenario) }}), file=p)
        shell: python
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/IntgDPGithubActionsDeployLambdaRole
          aws-region: eu-west-2
          role-session-name: UpdateWAF
      - name: Run Tests
        run: |
          aws lambda invoke --function-name dr2-e2e-tests-intg out --payload file://payload.json --log-type Tail --query 'LogResult' --output text --cli-binary-format raw-in-base64-out | base64 -d
